### ISSUE TITLE
Doc inaccuracy related to handler option WithCompression

### ISSUE THREAD

**Issue by jhump** [connectrpc/connect-go#492]
The [doc comment](https://github.com/bufbuild/connect-go/blob/main/option.go#L121) for `WithCompression` states:
```
Calling WithCompression with an empty name or nil constructors is a no-op.
```

However, tracing through the code, this is not true. The constructors are never checked for nil. Instead, any existing compressor previously registered with the same name is blindly overwritten with an invalid one. It is invalid because if _either_ constructor is nil and ends up needing to be used, it will cause a nil dereference panic in the `compressionPool` [here](https://github.com/bufbuild/connect-go/blob/main/compression.go#L70) and [here](https://github.com/bufbuild/connect-go/blob/main/compression.go#L73).

Perhaps this should instead behave like `WithAcceptCompression`? In that option, the constructors _are_ checked. But if they are both nil, it effectively unregisters the named compression algorithm (instead of being a no-op).

**Comment by akshayjshah** [comment]
Yep, definitely a bug. Suggested fix makes sense - I think we just need to return a nil from `newCompressionPool` in this case and add a test.
