### ISSUE TITLE
No error if the stream client connect  the bad server

### ISSUE THREAD

**Issue by koolay** [connectrpc/connect-go#563]
**Describe the bug**
 Connectrpc client request a bad server(the stream server not start), but not got a expected  network error.
**To Reproduce**
1. create a connectrpc client, and request with bad server url
2. got nil from the request

```go
import (
	"context"
	"fmt"
	"net/http"
	"testing"
	"time"

	"connectrpc.com/connect"
	"github.com/stretchr/testify/suite"
         ...
)

func (st *HubTestSuite) TestConnect() {
	connectClient := vmhubconnect.NewConnectionServiceClient(http.DefaultClient, "http://localhost:8019")
	stream, err := connectClient.Connect(st.ctx, connect.NewRequest(&vmhubv1.ConnectRequest{
		Name: "quickci-test",
	}))
	st.Nil(err) // Expect it should be failure

	for stream.Receive() {
		resp := stream.Msg()
		fmt.Println(resp.Greeting)
	}
}
```

**Environment (please complete the following information):**
- `connect-go`:  `v1.11.0`
- `go version`:  `go version go1.20 darwin/amd64`

**Additional context**

**Comment by akshayjshah** [comment]
Hi @koolay! You won't necessarily receive an error in the place you're expecting it, because the server has no obligation to send headers back to the client immediately. The client's view of a server-streaming RPC is an iterator (like `bufio.Scanner`), so you'll need to check for errors after exiting the Receive loop. Thorough error checking looks like this:

```go
connectClient := vmhubconnect.NewConnectionServiceClient(http.DefaultClient, "http://localhost:8019")
stream, err := connectClient.Connect(st.ctx, connect.NewRequest(&vmhubv1.ConnectRequest{
  Name: "quickci-test",
}))
if err != nil {
  panic(err)
}

for stream.Receive() {
  resp := stream.Msg()
  fmt.Println(resp.Greeting)
}
if err := stream.Err(); err != nil {
  panic(err)
}
if err := stream.Close(); err != nil {
  panic(err)
}
```
