### ISSUE TITLE
ctx.Done() when mounting services on Chi

### ISSUE THREAD

**Issue by ralphking** [connectrpc/connect-go#570]
**Describe the bug**

When Mounting a Service on another router (Chi in my case), ctx.Done() never happens when the client closes (I am using web, and I would expect a browser refresh or browser page close to cancel the context).

**To Reproduce**

Create a basic service + server, and call NewMyServiceHandler:
```
service MyService {
    rpc MyFunc(MyFuncRequest) returns (stream MyFuncResponse) {}
}
```

```
path, handler := myservicev1connect.NewMyServiceServiceHandler(myService)
```

Mount it on a Chi router:

```
r := chi.NewRouter()
r.Use(etc)
r.Route("/api", func(r chi.Router) {
    r.Mount(path, http.StripPrefix("/api", handler))
})
```

Inside the implementation:

```
select {
    case <-ctx.Done():
	return ctx.Err()
    default:
      doWork()
}
```

**Additional context**
This might just be due to my misunderstading of how Server streams are supposed to be closed/ended. Also, I suppose I am assuming that the request context from Chi is magically passed into the buf functions, which is probably where I am going wrong.

**Comment by emcfarlane** [comment]
Hey @ralphking, on the client in go calling [`Close`](https://pkg.go.dev/github.com/bufbuild/connect-go#ServerStreamForClient.Close) will drain the the  response body but not abort the request. To abort the client request using the web client you can use an `AbortController`, see this test for details: https://github.com/connectrpc/connect-es/blob/main/packages/connect-web-test/src/cancellation.spec.ts#L27 . Let me know if this solve it!

**Comment by emcfarlane** [comment]
Closing this issue as I think it's all working as expected. Please open again if the above doesn't solve the issue for you.
