### ISSUE TITLE
Expose deprecated option in interceptor

### ISSUE THREAD

**Issue by makasim** [connectrpc/connect-go#571]
**Is your feature request related to a problem? Please describe.**
It would allow us to implement an interceptor that logs the usage of deprecated endpoints.

**Describe the solution you'd like**

RPC specs provide a `deprecated` option that could be used on a method. Currently, Connect only added a deprecated comment. Exposing the value to interceptors could help to build more robust solutions.  

```
service CreateService {
  rpc Create(CreateRequest) returns (CreateResponse) {
    option deprecated = true;
  }
}
```

The solution I see: The option could be added to `connect.Spec`. That would be enough for this particular case. 

```
WrapUnary(unaryFunc connect.UnaryFunc) connect.UnaryFunc {
	return func(ctx context.Context, request connect.AnyRequest) (connect.AnyResponse, error) {
	    if request.Spec().Deprecated {
	       log.Printf("WARNING: %s is deprecated", request.Spec().Procedure)
	    }
            return unaryFunc(ctx, request)
	}
}
```

A more generic approach is to expose all the options in `connect.Spec` somehow (map?). In this case, we could add a custom option with a api removal date and set some alerts for it. 

**Describe alternatives you've considered**
-

**Additional context**
-

**Comment by akshayjshah** [comment]
Hey @makasim! Great suggestion - I've been meaning to expose the RPC's descriptor on `Spec`, which would give you access to `deprecated`, any custom options, and a bunch of other info.

In the meantime, you can get the descriptor yourself from the global registry: see [this comment on another issue](https://github.com/connectrpc/connect-go/issues/404#issuecomment-1328271332). `protoc-gen-connect-go` now generates constants for service names, so you shouldn't need a hard-coded string to look up the descriptor.

**Comment by makasim** [comment]
Looks like a global registry would solve my issue. Thank you for the hint!
