### ISSUE TITLE
What about Rust?

### ISSUE THREAD

**Issue by frederikhors** [connectrpc/connect-go#581]
_Sorry if I write in the golang package but this is the only for the backend I think._

What do you think about starting a `connect-rust`?

Rust is a very powerful and trending language.

Are you interested?

**Comment by akshayjshah** [comment]
> Sorry if I write in the golang package but this is the only for the backend I think.

That's fine! There's also `connect-es` for backends, but discussing this is okay. We're fully open to a Connect implementation in Rust, but we'd need strong community involvement - we're not the right people to develop a Rust project fully in-house. There's already https://github.com/AThilenius/axum-connect, which is headed in exactly the direction that makes sense to me - I'd suggest taking a look at that, filing issues, and contributing!

We'll have a better home for these discussions, and a better proposal process, in the next few weeks.

**Comment by frederikhors** [comment]
I'll wait for the the "better home" to subscribe and follow and I'll close this. Thanks!

**Comment by emcfarlane** [comment]
@frederikhors probably good to discuss here: https://github.com/orgs/connectrpc/discussions/7
