### ISSUE TITLE
If there is no package in the proto file, an unnecessary "." is added to the Path of the HTTP Handler.

### ISSUE THREAD

**Issue by dicenull** [connectrpc/connect-go#597]
## Describe the bug

When there is no package in the proto file, an unnecessary "." is added to the Path of the HTTP Handler. 
`ServeHTTP` will not be called because the path used in the branch and the path used in the implementation are generated differently.

## To reproduce

* coonnect-go v1.9.0

Reproducible with this branch.

- https://github.com/dicenull/connect-go/tree/unnecessary-dot

* Remove package specification from ping.proto.
* Run buf generate.
* ping.connect.go file is generated.
* For the `PingServiceName = "PingService"` constant, the `NewPingServiceHandler` method will result in `"/.PingService/"`.

## Comment

`service.Desc.ParentFile().Package()` is empty string and `. ` + `service.Desc.Name()`.
I think this bug occurs because this `reflectionName` and `service.Desc.FullName()` do not match.

```go
func reflectionName(service *protogen.Service) string {
  return fmt.Sprintf("%s.%s", service.Desc.ParentFile().Package(), service.Desc.Name())
}
```

* <https://github.com/connectrpc/connect-go/blob/065b6ad19e9243bb66472c20f88504fc3c8e9fbb/cmd/protoc-gen-connect-go/main.go#L514>

---

This text was translated from Japanese by DeepL.

<details>
<summary>Original text</summary>

## バグの説明

protoファイルにpackageがない場合、HTTP HandlerのPathに不要な"."が付与される。
分岐で使用するパスと、実装で使うパスが異なって生成されるため`ServeHTTP`が呼ばれなくなってしまう。

## 再現方法

* coonnect-go v1.9.0

このブランチで再現可能。

- https://github.com/dicenull/connect-go/tree/unnecessary-dot

* ping.proto のpackage指定を削除する。
* buf generateを実行する。
* ping.connect.goファイルが生成される。
* `PingServiceName = "PingService"`定数に対して、`NewPingServiceHandler`メソッドでは`"/.PingService/"`になっている。

## コメント

`service.Desc.ParentFile().Package()` が空文字列になり、`.` + `service.Desc.Name()`となってしまう。
この`reflectionName`と`service.Desc.FullName()`が一致しないため、このバグが発生していると思います。

```go
func reflectionName(service *protogen.Service) string {
  return fmt.Sprintf("%s.%s", service.Desc.ParentFile().Package(), service.Desc.Name())
}
```

* <https://github.com/connectrpc/connect-go/blob/065b6ad19e9243bb66472c20f88504fc3c8e9fbb/cmd/protoc-gen-connect-go/main.go#L514>

この文章は日本語をDeepLで翻訳した。
</details>

**Comment by emcfarlane** [comment]
Hey dicenull, thanks for the detailed breakdown and report!
