### ISSUE TITLE
Java support + does connect work with AWS API Gateway and Lambda?

### ISSUE THREAD

**Issue by skhreshefsharvit** [connectrpc/connect-go#618]
Use case:
An RPC server written in Go and a client written in Java, running on AWS with AWS API Gateway and Lambda.

Current state:
I use Twirp for the RPC server, but it doesn't have a maintained (or a finished) Java library.

I was wondering:
1. Does ConnectRPC support the combination of API Gateway and Lambda?
2. Is there a plan to write a Java library anytime soon? or maybe the compatibility with gRPC will make it possible to generate a gRPC client out of the Protobuf and run a connect-go RPC server in Go

**Comment by akshayjshah** [comment]
The Go implementation of Connect supports three RPC protocols: gRPC, gRPC-Web, and Connect's own protocol. The Connect _protocol_ works anywhere HTTP/1.1 works, so it should work with API Gateway + Lambda. If you have a Twirp server and client working, the Connect protocol will work too. You can call your API from Java using [`connect-kotlin`](https://github.com/connectrpc/connect-kotlin). Speak on on [this poll](https://github.com/orgs/connectrpc/discussions/11) if you need or want a pure Java implementation.

The gRPC _protocol_ requires support for HTTP trailers, which is often available only with HTTP/2. The last I checked, AWS API gateway <-> Lambda communication is HTTP/1.1-only but I don't know if it handles trailers correctly. **If it does support HTTP/1.1 with HTTP trailers,** then you can use a `grpc-java` client with a `connect-go` Lambda backend for request-response RPCs. The best way to check is to try it :)

**Comment by akshayjshah** [comment]
@skhreshefsharvit I'm going to close this issue because there doesn't seem to be anything to fix or patch. I hope your Lambda is up and running!
