### ISSUE TITLE
Streams support over http1?

### ISSUE THREAD

**Issue by Gictorbit** [connectrpc/connect-go#639]
Does it support gRPC streams over http1 using `websocket`?
I used this package to convert grpc streams to websocket [https://github.com/tmc/grpc-websocket-proxy](https://github.com/tmc/grpc-websocket-proxy)

**Comment by jhump** [comment]
@Gictorbit, no it does not. Bidirectional streams only work over HTTP/2. Connect implementations generally implement the specs for [gRPC](https://github.com/grpc/grpc/blob/master/doc/PROTOCOL-HTTP2.md), [gRPC-Web](https://github.com/grpc/grpc/blob/master/doc/PROTOCOL-WEB.md), and [Connect](https://connectrpc.com/docs/protocol/#streaming-rpcs), none of which make mention of web sockets. 

So when using HTTP 1.1, you are limited to server and client streams. If a server sees a request over HTTP 1.1 for a bidirectional streaming method, it will send a "505 HTTP Version Not Supported" error.

We may relax this in the future to _allow_ bidirectional streams over HTTP 1.1, thanks to the newly added support in `net/http` ([link](https://pkg.go.dev/net/http@master#ResponseController.EnableFullDuplex)). But even then, only half-duplex style streams can be guaranteed to work, as many peers may be unable to do full-duplex streaming with HTTP 1.1.
