### ISSUE TITLE
Allow disabling of generation subdirectory (place `*.connect.go` file in the base directory)

### ISSUE THREAD

**Issue by khalil-omer** [connectrpc/connect-go#641]
Apologies if I am misunderstanding as I am new to Connect, but [it seems](https://github.com/connectrpc/connect-go/blob/45625455d7dc24049956c74e632c7a7060656cef/cmd/protoc-gen-connect-go/main.go#L112) that you are hardcoding behavior that puts the generated code into a subdirectory. Is this necessary? `connect-es` does not do this. Please see the below screenshot showing my generated Go and TS code, where Connect code is in the `v1` directory for TS but a subdirectory for Go.

![CleanShot 2023-11-26 at 18 45 09](https://github.com/connectrpc/connect-go/assets/68179593/7b20802e-d382-476c-97cc-f021267c0856)

**Comment by emcfarlane** [comment]
See the discussion [here](https://github.com/connectrpc/connect-go/discussions/310) and please add any relevant feedback.
