### ISSUE TITLE
How to obtain underlying http Request?

### ISSUE THREAD

**Issue by domino14** [connectrpc/connect-go#653]
**Is your feature request related to a problem? Please describe.**
Inside an Interceptor, I don't have access to the underlying request. The request type is of type `connect.AnyRequest`; see for example this snippet:

```go
		return connect.UnaryFunc(func(
			ctx context.Context,
			req connect.AnyRequest,
		) (connect.AnyResponse, error) { ...
```

I am trying to get a Gorilla session stored in the request. The interface requires the http.Request:

```go
type Store interface {
	// Get should return a cached session.
	Get(r *http.Request, name string) (*Session, error)
...
```

**Describe the solution you'd like**
Ideally there would be a way to fetch the underlying http.Request

**Describe alternatives you've considered**
Alternatively I could implement the logic from gorilla/sessions and deal with the cookie in the http request directly, but this seems like duplicating work and I might as well implement the session logic entirely.

**Comment by jhump** [comment]
@domino14, the `*http.Request` is not made available to interceptors or handler code. You might instead do the session management/cookie access using HTTP middleware instead of a Connect interceptor.

Note that you could work-around the limitation with your own HTTP middleware that injects it into context. Something like so:
```go
// wrap your connect handler or entire mux with this
func requestInjectingMiddleware(handler http.Handler) http.Handler {
    return http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
        ctx := context.WithValue(r.Context(), httpRequestContextKey{}, r)
        handler.ServeHTTP(w, r.WithContext(ctx))
    })
}

// then use this to extract the request from the context in a connect interceptor
func getHTTPRequestFromContext(ctx context.Context) *http.Request {
	req, _ := ctx.Value(httpRequestContextKey{}).(*http.Request)
	return req // returns nil if no request in context
}

type httpRequestContextKey struct{}
```

**Comment by chrispine** [comment]
Closing this as resolved, but please reopen if needed. Thanks!

**Comment by domino14** [comment]
I meant to respond, sorry about that. I used a middleware to capture the request and store it in the context; almost identical to your solution. Thanks again.
