### ISSUE TITLE
How to add deadline to the service call context

### ISSUE THREAD

**Issue by juanpmarin** [connectrpc/connect-go#658]
Hi! It seems that if I set a timeout to the http server, like this:
```
httpServer := &http.Server{
  Addr:         address,
  Handler:      h2c.NewHandler(s.handler, &http2.Server{}),
  ReadTimeout:  20 * time.Second,
  WriteTimeout: 40 * time.Second,
}
```
the service call context is not cancelled, and it actually makes sense, but how can I assign a deadline to the context passed to every service call?

**Comment by jhump** [comment]
@juanpmarin, on the server, you can do this with an interceptor that modifies the context for each service call to add a timeout to it using [`context.WithTimeout`](https://pkg.go.dev/context#WithTimeout).

But note that if the _client_ sets a deadline on the context used to make the RPC (like using `context.WithTimeout` before making the call), it will be respected and the server context will already have a timeout, based on the time remaining in the client's context.

**Comment by juanpmarin** [comment]
@jhump thanks for you answer! Do you have an example of it? I don't find a way to propagate a new context using an interceptor

**Comment by jhump** [comment]
@juanpmarin, here's an example that applies a fixed timeout to every operation. Basically, you call `context.WithTimeout` to create a context with a deadline, and then pass that context up the chain.
```go
type timeoutInterceptor struct {
    timeout time.Duration
}
func (t *timeoutInterceptor) WrapUnary(next connect.UnaryFunc) connect.UnaryFunc {
    return func(ctx context.Context, req connect.AnyRequest) (connect.AnyResponse, error) {
        if req.Spec().IsClient {
            // Not doing anything for client-side invocations
            return next(ctx, req)
        }
        ctx, cancel := context.WithTimeout(t.timeout)
        defer cancel()
        return next(ctx, req)
    }
}
func (t *timeoutInterceptor) WrapStreamingClient(next connect.StreamingClientFunc) connect.StreamingClientFunc {
    // Not doing anything for client-side invocations, so no wrapping needed
    return next
}
func (t *timeoutInterceptor) WrapStreamingHandler(next connect.StreamingHandlerFunc) connect.StreamingHandlerFunc {
    return func(ctx context.Context, stream connect.StreamingHandlerConn) error {
        ctx, cancel := context.WithTimeout(t.timeout)
        defer cancel()
        return next(ctx, stream)
    }
}
```

**Comment by juanpmarin** [comment]
Awesome! Thanks

**Comment by chrispine** [comment]
Sounds like this is resolved, but please reopen if not. Thanks!
