### ISSUE TITLE
Doesn't work with mocked HTTP client

### ISSUE THREAD

**Issue by a-porubai** [connectrpc/connect-go#666]
**Describe the bug**

Hello! I try to use mocked HTTP client for testing. 
After request to grpc client and it blocks and I don't get a response or error

**To Reproduce**

pass custom HTTP client to grpc client:
func (g *GrpcClientProvider) AccountingInternal() internal_apiv1connect.AccountingInternalServiceClient {
	return internal_apiv1connect.NewAccountingInternalServiceClient(g.builder.httpClient, g.builder.accountingInternalUrl,
		g.GetClientOptions()...)
}

**Comment by emcfarlane** [comment]
Hello @a-porubai ! Could you please provide more details about the mocked client and a full reproducible example to run?  The client must obey the `Do` behaviour, please see the [docs](https://pkg.go.dev/net/http#Client.Do). We might be able to help debug the mocked client in the buf [slack room](https://join.slack.com/t/bufbuild/shared_invite/zt-29qws2tmu-blqHHI1dThKhuEw9pwLDxQ).

**Comment by emcfarlane** [comment]
https://bufbuild.slack.com/archives/CRZ680FUH/p1704205957554459
