### ISSUE TITLE
Missing Go package metadata on connectrpc.com

### ISSUE THREAD

**Issue by GeertJohan** [connectrpc/connect-go#687]
**Describe the bug**

The new import paths based on connectrpc.com cause errors when using with standard go tools. It seems that the website returns a 404 for valid import paths and is missing the `<meta name="go-import" ...>`  information in it's body.

**To Reproduce**

```
$ go list -m -versions -json connectrpc.com/connect/cmd/protoc-gen-connect-go
go: unrecognized import path "connectrpc.com/connect/cmd/protoc-gen-connect-go": reading https://connectrpc.com/connect/cmd/protoc-gen-connect-go?go-get=1: 404 Not Found
```

It would be nice if the website could return the metadata and/or redirect to https://pkg.go.dev/connectrpc.com/connect/cmd/protoc-gen-connect-go (I think that's how google.golang.org handles it, by just 302 redirecting to pkg.go.dev).

Please see https://pkg.go.dev/cmd/go (ctrl+f for `?go-get=1`).

**Additional context**

I'm using [mise](github.com/jdx/mise) to install tools. It relies on `go list -m -versions -json` to obtain module/package information. This works great for domains like github.com and google.golang.org, but fails for connectrpc.com.

**Comment by jhump** [comment]
@GeertJohan, the server _does_ in fact return the correct metadata. But it does not do so for every package in the module. It is only necessary to provide that metadata for the _root_ of the module.

The problem you're hitting is that you are using the `-m` and `-versions` arguments, which are for _modules_, not packages. But the import path you indicated `connectrpc.com/connect/cmd/protoc-gen-connect-go` is not a module. It is a package inside the `connectrpc.com/connect` module.

So the following do work:
```
go get connectrpc.com/connect/cmd/protoc-gen-connect-go
go install connectrpc.com/connect/cmd/protoc-gen-connect-go
go list -json connectrpc.com/connect/cmd/protoc-gen-connect-go
go list connectrpc.com/connect/...
```

And if you want to see the versions of `protoc-gen-connect-go`, you have to get the version metadata for the enclosing module:
```
go list -m -versions -json connectrpc.com/connect
```

**Comment by GeertJohan** [comment]
Hi @jhump thanks for your fast response!

I understand that the `go list` is supposed to be called with a module. It is impossible to detect by just the import path string whether it is a module root or a package. The examples you provided don't error but also don't give any hints to where the module root is located. So `mise` iterates over the path by removing the last part until a module is detected via `go list -m ..`. For other domains this doesn't error, `go list` returns with exit code 0, but does not provide a list of versions (since it was called with an import path that was not a module). This works fine for github and other domains, for example `go list -m -versions -json github.com/go-task/task/v3/cmd/task` does not return an error. I'm not entirely sure how that even works though, I just discovered github also serves a 404 without go-import metadata on `http://github.com/go-task/task/v3/cmd/task?go-get=1`, so I'm a little confused now.. Perhaps they're detecting the User-Agent and serve a different result based on that? Any ideas?

**Comment by GeertJohan** [comment]
I think the downside using that command is that it can't be called without having an active go module and needing to already have `go get` the package. It's a lot cheaper to traverse the path until accidentally hitting the module.

**Comment by akshayjshah** [comment]
> I suspect go get does exactly as you describe already: it traverses the path until it finds the module. So it probably tries the given path, and, if it cannot be resolved, it peels off a path element from the right and tries again, and repeats until it finds a valid module.

I believe that's true, and that it's new behavior since the introduction of Go modules (which I guess are pretty old now).

**Comment by GeertJohan** [comment]
What `go-list.sh` does is basically what `mise` does right now, except that go-list.sh ignores the errors from `go list` calls.
It works, and is a way to work around the inconsistency. That could be duplicated in mise, although in general I think errors shouldn't be ignored, especially not when they're inconsistent. It would probably be good for the Go project to be more explicit on the design/implementation-specs of the metadata for packages. The inconsistency now makes that `go list -m -versions -json helm.sh/helm/v3/cmd/helm` responds different than `go list -m -versions -json connectrpc.com/connect/cmd/protoc-gen-go`.

Also it would be useful for `go list -m -json` to output the module path.

I'll head over to the go repo to write an issue. Any other thoughts/ideas I should take?

It would be nice if connectrpc.com could add the metadata on the package page as well, although I also agree it's not very well specified and may be better to wait for specs before making the effort. Thanks @jhump !
