### ISSUE TITLE
Any non mux router support for connectrpc?

### ISSUE THREAD

**Issue by tahadostifam** [connectrpc/connect-go#752]
Hi, Recently i've been using `connectrpc` to handle my `json-rpc gateway` and i realized `connectrpc` does not support non `http.ServeMux` router, right?

Let me know i'm wrong!

**Comment by emcfarlane** [comment]
Connect-go does support any router that implements the net/http [Handler](https://pkg.go.dev/net/http#Handler) method. For example in the docs for [routing](https://pkg.go.dev/net/http#Handler) the generated handler return the route prefix and a `http.Handler` which can be directly passed to a server mux. See the generated [`NewPingServiceHandler`](https://github.com/connectrpc/connect-go/blob/main/internal/gen/connect/ping/v1/pingv1connect/ping.connect.go#L188) for reference to the type signature. Closing, but feel free to ask more questions about specific routers.

**Comment by tahadostifam** [comment]
So is there any solution to handle my `connectrpc` with gin?
Sorry but i'm a little confused😅

**Comment by emcfarlane** [comment]
For `gin` use the [`WrapH`](https://pkg.go.dev/github.com/gin-gonic/gin#WrapH) to register to the gin handler. This will look something like:
```go
router := gin.Default()
pingServiceRoute, pingServiceHandler := pingv1connect.NewPingServiceHandler()
router.POST(pingServiceRoute, gin.WrapH(pingServiceHandler))
```

**Comment by tahadostifam** [comment]
I got it.
Thank you so much Edward😄❤️🤌🏿
