### ISSUE TITLE
add gzip option for server side

### ISSUE THREAD

**Issue by czyt** [connectrpc/connect-go#773]
current we can use the code 
```go
client := lynxv1connect.NewLynxServiceClient(
		http.DefaultClient,
		"http://localhost:8080",
		connect.WithSendGzip(),
	)
```
but for the server side
```go
mux := http.NewServeMux()
path, handler := lynxv1Connect.NewLynxServiceHandler(lynxSvr, connect.WithCompression(?,?,?))
```
it seems un-documented which name to use and ensure it is right ,and i did not found this in tests of this repo,I think a Option for server side is needed.

**Comment by jhump** [comment]
No options are needed on the server side. This is all documented:

https://connectrpc.com/docs/go/serialization-and-compression#compression

and

https://pkg.go.dev/connectrpc.com/connect#WithCompression

> By default, handlers support gzip using the standard library's [compress/gzip](https://pkg.go.dev/compress/gzip) package at the default compression level. To remove support for a previously-registered compression algorithm, use WithCompression with nil decompressor and compressor constructors.

**Comment by czyt** [comment]
thanks.
