### ISSUE TITLE
Performance of Connect vs gRPC

### ISSUE THREAD

**Issue by singh-hovr** [connectrpc/connect-go#784]
I have just read the following article: https://kmcd.dev/posts/benchmarking-go-grpc/
It seems like connect performance is considerably slow compare to standard gRPC. Is there a specific reason for this? 
Can it be improved ?

**Comment by jhump** [comment]
@singh-hovr, most of the difference is due to the fact that connect-go is based on `net/http`, whereas grpc-go includes a bespoke HTTP/2 implementation (for both client and server). We wanted Connect to be a lighter-weight dependency that interoperates with the rest of the Go server ecosystem (including things like HTTP/3 support, HTTP middleware, etc), and it's performance will improve as the performance of `net/http` improves over time in future Go releases.

**Comment by singh-hovr** [comment]
Thank you for the response, I have a another question around syntax. When writing clients we usually have to do something 
```
res, err := client.Greet(
		context.Background(),
		connect.NewRequest(&greetv1.GreetRequest{Name: "Jane"}),
	)
```  
Why don't create a wrapper for methods to convert the request to connect.NewRequest so final syntax looks user friendly:
```
res, err := client.Greet(
		context.Background(),
		&greetv1.GreetRequest{Name: "Jane"},
	)
```
Or we can provide the opt to create these wrappers. You thoughts?

**Comment by jhump** [comment]
@singh-hovr, there is already a discussion on that topic: https://github.com/connectrpc/connect-go/discussions/421. The connect-go maintainers have discussed this somewhat recently, but we still don't have any concrete plans on how to address this ergonomics issue (and thus no timeline yet either).

**Comment by singh-hovr** [comment]
I can create a PR for wrapping the request and response in the generate code and provide option to create in same Dir? Would you be open to that?

**Comment by singh-hovr** [comment]
I have created the wrapper and it works. While trying to put the file in same directory, I am getting the following error:
panic: runtime error: invalid memory address or nil pointer dereference:  segmentation violation
for exampleServiceServiceDescriptor. What think might be the issue?

**Comment by bufdev** [comment]
@jhump has already indicated there is another issue open for this. It's unrealistic to ask anyone to debug your code without reproduction steps. We likely are not open for PR on this issue at this time, however.
